### ISSUE TITLE
Swagger docs do not appear correctly after fetching static files

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#133] opened 2017-06-16 21:32 UTC
Swagger docs do not appear correctly when navigating to `<TBS_HOST>/swagger`. Instructions to fetch files located in [readme](https://github.com/3Blades/app-backend/blob/master/README.md).

**Comment by jkp85** [comment] 2017-06-22 15:03
Already fixed

**Comment by jkp85** [comment] 2017-06-22 15:05
@jgwerner Cannot reproduce, can you verify?

**Comment by jgwerner** [comment] 2017-06-22 15:59
@jkp85 Seems to work now. Closing.

**Comment by jgwerner** [comment] 2017-06-22 21:50
Bug re appeared in dev 😭

**Comment by jgwerner** [comment] 2017-06-22 21:54
Example path that is does not find: https://dev.3blades.io/static/rest_framework_swagger/lib/swagger-oauth.js

**Comment by johngriebel** [comment] 2017-07-07 14:30
It appears that the files within a Docker container are only available to that container specifically. What that means is that after running `python manage.py collectstatic`, the files copied to `/srv/app/static` are only available to the container running app-backend. As far as the openresty container is concerned, `/srv/` is still empty. Thus, the static files must be copied from one container to the other, as follows:
`sudo docker cp deployment_api_1:/srv/app/static .`
`sudo docker cp static deployment_server_1:/srv/app/static`

It may be possible to copy the files directly from one container to another, but the documentation doesn't explicitly state that it is.

**Comment by johngriebel** [comment] 2017-07-10 16:57
Closing this as we have a solution, and don't currently need static files although we may in the future. If this does come up again, and issue should be opened in the devops repository.

**Closed by johngriebel** 2017-07-10 16:57 UTC
Labels: fix
