### ISSUE TITLE
Cannot access stats or run-stats of server created in projects

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#224] opened 2017-07-18 14:26 UTC
Trying to retrieve the `run-stats` and `stats` of a server created under a project. Am using the `admin` namespace, and am using the project `testing`. The server name is `TestServer`. When I try to access the links below using the ids from the project and server instances:

https://dev-api.3blades.ai/v1/admin/projects/8f58ea26-8ea0-40df-a551-b6a95d4e6a00/servers/8b476be5-4324-413a-b2e6-1992b830f295/stats/

https://dev-api.3blades.ai/v1/admin/projects/8f58ea26-8ea0-40df-a551-b6a95d4e6a00/servers/8b476be5-4324-413a-b2e6-1992b830f295/run-stats/

you get an error saying `'dict' object has no attribute 'server'` .

You can replicate this error by logging into a valid namespace, creating a project, creating a resource, creating a server using that resource, and by going to the `stats` or `run-stats` URL like in the links above.

**Comment by johngriebel** [comment] 2017-07-20 12:57
Shouldn't have been automatically closed.

**Comment by johngriebel** [comment] 2017-07-20 13:04
@pthakkar230 This has been merged, can you re-deploy and re-test to confirm the issue is fixed?

**Comment by pthakkar230** [comment] 2017-07-20 15:08
The server `stats` and `run-stats` are created successfully, but when I go to retrieve them by `id` or try to delete them, I get a 404 error.

Here are logs: https://www.runscope.com/radar/vzxz7svfdhxu/56f017f6-e7dc-4e50-85d9-8d653f70e969/history/5b132b5c-b9df-444c-8c6f-ea3766d1cd2d

**Comment by johngriebel** [comment] 2017-07-24 12:29
@pthakkar230 Since `stats` and `run-stats` are aggregations of statistics about the server in question, these records should not be accessed by their `id` directly. Because of this, `stats` and `run-stats` records cannot be deleted, except by deleting the server itself. I am going to close this issue now.

**Closed by johngriebel** 2017-07-24 12:29 UTC
Labels: fix
